### ISSUE TITLE
SWI image

### ISSUE THREAD

**Issue by marinagrprat** [CAIsr/qsm#16]
Hello,

I was wondering wheather I can use the SWI magnitude and phase images as input for the QSM reconstruction instead of the gradient echo data (GRE). I have done it and I was able to obtain the QSM final map. Do you know if I can rely on those results? 

Thank you so much,

Marina.

**Comment by stebo85** [comment]
Dear @marinagrprat,

Using the SWI phase images is not a good idea, because SWI is filtered and removes a lot of information. You should always use the unfiltered GRE phase for QSM processing.

This is how an SWI filtered phase looks like (and this is NOT usable for QSM!):
![image](https://user-images.githubusercontent.com/4021595/189243730-3abdf984-85db-4283-9cf4-f964aa426c66.png)

This is how the unfiltered phase should look like (which is the required input for QSM):
![image](https://user-images.githubusercontent.com/4021595/189243785-73fd8b54-264e-42fd-98e8-2086c69c36fb.png)

Kind regards
Steffen
