### ISSUE TITLE
Single pass

### ISSUE THREAD

**Issue by marinagrprat** [CAIsr/qsm#17]
Hi,

I have tried running the QSM reconstruction using the _--single_pass_ option. I would like to know what is the exact difference If I use this option or not. From what I understand, if I use the single pass option it runs a single QSM reconstruction per echo instead of two, so for the reconstruction it uses a mask produced by thresholding and binarising the magnitude signal, but it is skipping the second reconstruction which applies morphological operations. Is that correct?

Thank you so much,

Marina.

**Comment by stebo85** [comment]
Dear @marinagrprat,

I am assuming that you are talking about QSMxT and not the TGV QSM pipeline (this issue was opened in https://github.com/CAIsr/qsm/ -> QSMxT is here: https://github.com/QSMxT/QSMxT).

If my assumption is correct, then it will depend on the version of QSMxT. Again, I am making an assumption that you are running the latest version 1.1.13 https://github.com/QSMxT/QSMxT/releases/tag/v1.1.13

In the latest version of QSMxT you are correct:  with the single pass option it runs a single QSM reconstruction per echo instead of two. 

by default QSMxT is not using the magnitude signal in 1.1.13, but is using the phase to compute a mask, but you can change this if it doesn't work for you (even BET is an option).

The second pass takes the mask from the first run and attempts to fill holes and missing bits of the mask. Then it runs another QSM processing on this larger mask. Then the two QSM reconstructions are combined where the first pass is used whenever possible and the second pass is used to fill in the missing information. This then results in a QSM reconstruction with considerably less artifacts:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/4021595/189243485-04942f9c-19dc-4b9e-a89f-a512cf27dd39.png">


Full details are available here: https://onlinelibrary.wiley.com/doi/abs/10.1002/mrm.29048

Kind regards
Steffen
